"""
Hardcoded Nifty 500 constituent list as Yahoo Finance tickers.

Each entry is an NSE symbol with the ".NS" suffix so it can be passed
directly to yfinance (the price-data source used across this project).

Notes:
- Index membership changes over time. Update this list when NSE
  publishes a revised Nifty 500 constituents file.
- Use `get_nifty500_symbols()` to get a de-duplicated, sorted copy.
"""
from typing import List

# Base NSE symbols (without the .NS suffix). Kept sorted for easy diffing.
_NIFTY_500_BASE = [
    "360ONE", "3MINDIA", "ABB", "ACC", "ACMESOLAR", "AIAENG", "APLAPOLLO",
    "AUBANK", "AWL", "AADHARHFC", "AARTIIND", "AAVAS", "ABBOTINDIA",
    "ACE", "ADANIENSOL", "ADANIENT", "ADANIGREEN", "ADANIPORTS", "ADANIPOWER",
    "ATGL", "ABCAPITAL", "ABFRL", "ABREL", "ABSLAMC", "AEGISLOG", "AFCONS",
    "AFFLE", "AJANTPHARM", "AKUMS", "APLLTD", "ALKEM", "ALKYLAMINE",
    "ALOKINDS", "ARE&M", "AMBER", "AMBUJACEM", "ANANDRATHI", "ANANTRAJ",
    "ANGELONE", "APARINDS", "APOLLOHOSP", "APOLLOTYRE", "APTUS", "ASAHIINDIA",
    "ASHOKLEY", "ASIANPAINT", "ASTERDM", "ASTRAZEN", "ASTRAL", "ATUL",
    "AUROPHARMA", "AIIL", "DMART", "AXISBANK", "BASF", "BEML", "BLS",
    "BSE", "BAJAJ-AUTO", "BAJFINANCE", "BAJAJFINSV", "BAJAJHLDNG",
    "BALKRISIND", "BALRAMCHIN", "BANDHANBNK", "BANKBARODA", "BANKINDIA",
    "MAHABANK", "BATAINDIA", "BAYERCROP", "BERGEPAINT", "BDL", "BEL",
    "BHARATFORG", "BHEL", "BPCL", "BHARTIARTL", "BHARTIHEXA", "BIKAJI",
    "BIOCON", "BSOFT", "BLUEDART", "BLUESTARCO", "BBTC", "BOSCHLTD",
    "FIRSTCRY", "BRIGADE", "BRITANNIA", "MAPMYINDIA", "CCL", "CESC",
    "CGPOWER", "CRISIL", "CAMPUS", "CANFINHOME", "CANBK", "CAPLIPOINT",
    "CGCL", "CARBORUNIV", "CASTROLIND", "CEATLTD", "CELLO", "CENTRALBK",
    "CDSL", "CENTURYPLY", "CERA", "CHALET", "CHAMBLFERT", "CHENNPETRO",
    "CHOLAHLDNG", "CHOLAFIN", "CIPLA", "CUB", "CLEAN", "COALINDIA",
    "COCHINSHIP", "COFORGE", "COLPAL", "CAMS", "CONCORDBIO", "CONCOR",
    "COROMANDEL", "CRAFTSMAN", "CREDITACC", "CROMPTON", "CUMMINSIND",
    "CYIENT", "DCMSHRIRAM", "DLF", "DABUR", "DALBHARAT", "DATAPATTNS",
    "DEEPAKFERT", "DEEPAKNTR", "DELHIVERY", "DEVYANI", "DIVISLAB",
    "DIXON", "LALPATHLAB", "DRREDDY", "EIDPARRY", "EIHOTEL", "EASEMYTRIP",
    "EICHERMOT", "ELECON", "ELGIEQUIP", "EMAMILTD", "EMCURE", "ENDURANCE",
    "ENGINERSIN", "ERIS", "ESCORTS", "ETERNAL", "EXIDEIND", "NYKAA",
    "FEDERALBNK", "FACT", "FINCABLES", "FINPIPE", "FSL", "FIVESTAR",
    "FORTIS", "GAIL", "GVT&D", "GMRAIRPORT", "GRSE", "GICRE", "GILLETTE",
    "GLAND", "GLAXO", "GLENMARK", "MEDANTA", "GODIGIT", "GPIL",
    "GODFRYPHLP", "GODREJAGRO", "GODREJCP", "GODREJIND", "GODREJPROP",
    "GRANULES", "GRAPHITE", "GRASIM", "GRAVITA", "GESHIP", "FLUOROCHEM",
    "GUJGASLTD", "GMDCLTD", "GNFC", "GPPL", "GSPL", "HEG", "HBLENGINE",
    "HCLTECH", "HDFCAMC", "HDFCBANK", "HDFCLIFE", "HFCL", "HAPPSTMNDS",
    "HAVELLS", "HEROMOTOCO", "HSCL", "HINDALCO", "HAL", "HINDCOPPER",
    "HINDPETRO", "HINDUNILVR", "HINDZINC", "POWERINDIA", "HOMEFIRST",
    "HONASA", "HONAUT", "HUDCO", "HYUNDAI", "ICICIBANK", "ICICIGI",
    "ICICIPRULI", "IDBI", "IDFCFIRSTB", "IFCI", "IIFL", "INOXINDIA",
    "IRB", "IRCON", "ITC", "ITI", "INDGN", "INDIACEM", "INDIAMART",
    "INDIANB", "IEX", "INDHOTEL", "IOC", "IOB", "IRCTC", "IRFC",
    "IREDA", "IGL", "INDUSTOWER", "INDUSINDBK", "NAUKRI", "INFY",
    "INOXWIND", "INTELLECT", "INDIGO", "IGIL", "IKS", "IPCALAB",
    "JBCHEPHARM", "JKCEMENT", "JBMA", "JKTYRE", "JMFINANCIL", "JSWENERGY",
    "JSWHL", "JSWINFRA", "JSWSTEEL", "JPPOWER", "J&KBANK", "JINDALSAW",
    "JSL", "JINDALSTEL", "JIOFIN", "JUBLFOOD", "JUBLINGREA", "JUBLPHARMA",
    "JWL", "JUSTDIAL", "JYOTHYLAB", "JYOTICNC", "KPRMILL", "KEI",
    "KNRCON", "KPITTECH", "KAJARIACER", "KPIL", "KALYANKJIL", "KANSAINER",
    "KARURVYSYA", "KAYNES", "KEC", "KFINTECH", "KIRLOSBROS", "KIRLOSENG",
    "KOTAKBANK", "KIMS", "LTF", "LTTS", "LICHSGFIN", "LTFOODS", "LTIM",
    "LT", "LATENTVIEW", "LAURUSLABS", "LEMONTREE", "LICI", "LINDEINDIA",
    "LLOYDSME", "LUPIN", "MMTC", "MRF", "LODHA", "MGL", "MAHSEAMLES",
    "M&MFIN", "M&M", "MANAPPURAM", "MRPL", "MANKIND", "MARICO", "MARUTI",
    "MASTEK", "MFSL", "MAXHEALTH", "MAZDOCK", "METROPOLIS", "MINDACORP",
    "MSUMI", "MOTILALOFS", "MPHASIS", "MCX", "MUTHOOTFIN", "NATCOPHARM",
    "NBCC", "NCC", "NHPC", "NLCINDIA", "NMDC", "NSLNISP", "NTPCGREEN",
    "NTPC", "NH", "NATIONALUM", "NAVA", "NAVINFLUOR", "NESTLEIND",
    "NETWEB", "NETWORK18", "NEULANDLAB", "NEWGEN", "NAM-INDIA", "NIVABUPA",
    "NUVAMA", "OBEROIRLTY", "ONGC", "OIL", "OLAELEC", "OLECTRA",
    "PAYTM", "OFSS", "POLICYBZR", "PCBL", "PGEL", "PIIND", "PNBHOUSING",
    "PNCINFRA", "PTCIL", "PVRINOX", "PAGEIND", "PATANJALI", "PERSISTENT",
    "PETRONET", "PFIZER", "PHOENIXLTD", "PIDILITIND", "PEL", "PPLPHARMA",
    "POLYMED", "POLYCAB", "POONAWALLA", "PFC", "POWERGRID", "PRAJIND",
    "PREMIERENE", "PRESTIGE", "PGHH", "PNB", "QUESS", "RRKABEL",
    "RBLBANK", "RECLTD", "RHIM", "RITES", "RADICO", "RVNL", "RAILTEL",
    "RAINBOW", "RKFORGE", "RCF", "RTNINDIA", "RAYMONDLSL", "RAYMOND",
    "REDINGTON", "RELIANCE", "RPOWER", "ROUTE", "SBFC", "SBICARD",
    "SBILIFE", "SJVN", "SKFINDIA", "SRF", "SAGILITY", "SAILIFE",
    "MOTHERSON", "SAMMAANCAP", "SAPPHIRE", "SARDAEN", "SAREGAMA",
    "SCHAEFFLER", "SCHNEIDER", "SCI", "SHREECEM", "RENUKA", "SHRIRAMFIN",
    "SHYAMMETL", "SIEMENS", "SIGNATURE", "SOBHA", "SOLARINDS", "SONACOMS",
    "SONATSOFTW", "STARHEALTH", "SBIN", "SAIL", "SWSOLAR", "SUMICHEM",
    "SUNPHARMA", "SUNTV", "SUNDARMFIN", "SUNDRMFAST", "SUPREMEIND",
    "SUZLON", "SWANENERGY", "SWIGGY", "SYNGENE", "SYRMA", "TBOTEK",
    "TVSMOTOR", "TVSSCS", "TANLA", "TATACHEM", "TATACOMM", "TCS",
    "TATACONSUM", "TATAELXSI", "TATAINVEST", "TATAMOTORS", "TATAPOWER",
    "TATASTEEL", "TATATECH", "TTML", "TECHM", "TECHNOE", "TEJASNET",
    "NIACL", "RAMCOCEM", "THERMAX", "TIMKEN", "TITAGARH", "TITAN",
    "TORNTPHARM", "TORNTPOWER", "TARIL", "TRENT", "TRIDENT", "TRIVENI",
    "TRITURBINE", "TIINDIA", "UCOBANK", "UNOMINDA", "UPL", "UTIAMC",
    "ULTRACEMCO", "UNIONBANK", "UBL", "UNITDSPR", "USHAMART", "VGUARD",
    "DBREALTY", "VTL", "VBL", "MANYAVAR", "VEDL", "VIJAYA", "VMM",
    "IDEA", "VOLTAS", "WAAREEENER", "WELCORP", "WELSPUNLIV", "WESTLIFE",
    "WHIRLPOOL", "WIPRO", "WOCKPHARMA", "YESBANK", "ZFCVINDIA",
    "ZEEL", "ZENTEC", "ZENSARTECH", "ZYDUSLIFE", "ECLERX",
]


def get_nifty500_symbols(suffix: str = ".NS") -> List[str]:
    """
    Return the Nifty 500 constituents as Yahoo Finance tickers.

    Args:
        suffix: Exchange suffix appended to each base symbol.
                Defaults to ".NS" for NSE (Yahoo Finance India).

    Returns:
        De-duplicated, sorted list of tickers, e.g. "RELIANCE.NS".
    """
    unique_bases = sorted(set(_NIFTY_500_BASE))
    return [f"{base}{suffix}" for base in unique_bases]


# Convenience constant: full Yahoo ticker list.
NIFTY_500_SYMBOLS = get_nifty500_symbols()
